#!/sbin/sh
# $Id:
#
# Boot wrapper to run olc service startup script


STARTUP_SCRIPT=/cpg/3rdParty/STARTUP_SCRIPTs/cpg/general/serviceStartup.sh

case "$1" in
'start')
		if [ -x ${STARTUP_SCRIPT} ]; then
				echo 'olc services starting.'
				${STARTUP_SCRIPT}
		fi
		;;

'install')
		SCRIPT=${dirname $0)/olc_services
		if diff ${SCRIPT} /etc/init.d/olc_services &>/dev/null; then
			cp ${SCRIPT} /etc/init.d
		fi
		if [ ! -f /etc/rc3.d/S99olc_services ]; then
			rm -f /etc/rc3.d/S??olc_services
			ln /etc/init.d/olc_services /etc/rc3.d/S99olc_services
		fi
		;;

*)
		echo "Usage: $0 { start | install }"
		exit 1
		;;

esac
exit 0
