#!/usr/bin/bash
#
# bart_runner:	bill.thorsteinson@innovapost.com (10/31/17)
# -------------------------------------------
# BART wrapper to be run instead of using cron
#   Intended to be run by SMF.
#
# Modified 10/31/17: Initial version. 
# Modified 11/01/17: Add visible bart string to sleep command; makes greping processes easier

# Specify hour as value from 1 to 12.  Runs twice daily during specified hour
RUN_HOUR=6

BART_LOG=/usr/local/sbin/bartlog

# Loop forever waiting most of an hour between run attempts
while true; do 
	if [[ ${RUN_HOUR} -eq $(date +%l) ]]; then
		${BART_LOG}
	fi
	# Wait most of an hour - needs to be long enough that bartlog does't run twice the same hour
	sleep 3550 bart_runner
done

# EOF
